# Site settings
title: More than a feeling
email: tikaltikal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the homepage of Andre Hogenkamp |
  Senior Software Engineer @ VXCompany |
  I am a fullstack programmer
baseurl: "/" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tikal86
github_username:  tikal86

# Build settings
markdown: kramdown

